// ========== 多媒体配置 ==========
export const MEDIA_CONFIG = {
  // 抓取配置
  MAX_RESOLVE_ITEMS: 20,        // 后台异步解析图片的上限（从80降低，避免拖慢下轮缓存填充）
  RESOLVE_TIMEOUT: 10000,       // 抓取超时（毫秒，从15秒降低到10秒，快速失败）
  USE_SCRAPLING: true,          // 启用 Scrapling 动态渲染（从false改为true）
  SCRAPLING_MODE: 'dynamic',    // Scrapling 模式（basic/dynamic/stealth）
  SCRAPLING_TIMEOUT: 18000,     // Scrapling 超时（毫秒，从15秒提高到18秒）

  // 图片评分阈值：宁可少图，也不要 logo / 小图标 / 默认图污染资讯卡片
  MIN_IMAGE_SCORE: 32,
  MIN_IMAGE_WIDTH: 320,
  MIN_IMAGE_HEIGHT: 180,
  ASPECT_RATIO_MIN: 0.8,
  ASPECT_RATIO_MAX: 3.2,

  // 缓存配置
  IMAGE_CACHE_SIZE: 2000,       // 缓存条目数量（从1000提高到2000）
  IMAGE_CACHE_TTL: 7200000,     // 缓存有效期（2小时，从1小时提高）

  // 图片去重配置
  MAX_IMAGE_REUSE: 1,           // 同一图片最多使用次数（从2降低到1，避免重复）
};

// ========== 信息源质量权重 ==========
// 从顶级项目（Horizon/TrendRadar）学到的：给不同质量源设置权重，高权重源优先展示
export const SOURCE_WEIGHTS = {
  // 顶刊/政府/顶级实验室/AI官方博客（权重1.0）
  'Amazon AI Blog': 1.0,
  'Amazon Science': 1.0,
  'Anthropic News': 1.0,
  'Apple Machine Learning': 1.0,
  'Bloomberg Markets': 1.0,
  'CNBC Markets': 1.0,
  'CMU RI': 1.0,
  'DARPA News': 1.0,
  'Financial Times Markets': 1.0,
  'Google AI Blog': 1.0,
  'Google DeepMind': 1.0,
  'Google Research Blog': 1.0,
  'IBM Research': 1.0,
  'Meta AI Blog': 1.0,
  'Meta AI Research (FAIR)': 1.0,
  'Microsoft AI Blog': 1.0,
  'Microsoft Research': 1.0,
  'Microsoft Research AI': 1.0,
  'MIT CSAIL': 1.0,
  'NVIDIA AI Blog': 1.0,
  'NIST Technology': 1.0,
  'Nature': 1.0,
  'Nature Biotechnology': 1.0,
  'Nature Machine Intelligence': 1.0,
  'Nature Medicine': 1.0,
  'OpenAI Blog': 1.0,
  'Reuters Finance': 1.0,
  'Science Advances': 1.0,
  'Science Magazine': 1.0,
  'Stanford HAI': 1.0,
  'Stanford SAIL': 1.0,
  'UC Berkeley BAIR': 1.0,
  'Wall Street Journal': 1.0,
  '中国法院网': 1.0,
  '科技部': 1.0,
  '工信部': 1.0,
  // 学术源（权重0.95）
  'ArXiv CS AI': 0.95,
  'ArXiv CS CL': 0.95,
  'ArXiv CS CV': 0.95,
  'ArXiv CS ML': 0.95,
  'ArXiv CS NE': 0.95,
  'ArXiv CS RO': 0.95,
  'ArXiv Quantitative Finance': 0.95,
  '第一财经': 0.95,
  '财新网': 0.95,
  // 高权重源（权重0.9）
  'Hacker News Best': 0.9,
  'IEEE Spectrum': 0.9,
  'MIT News AI': 0.9,
  'MIT News Tech': 0.9,
  '华尔街见闻': 0.9,
  // 优质源（权重0.85）
  'ACM TechNews': 0.85,
  'GitHub Blog': 0.85,
  'GitHub Engineering': 0.85,
  'Hacker News': 0.85,
  'KrebsOnSecurity': 0.85,
  'MIT Technology Review': 0.85,
  'Quanta Magazine': 0.85,
  'Science Daily': 0.85,
  'Seeking Alpha': 0.85,
  'Semiconductor Engineering': 0.85,
  '中国证券报': 0.85,
  '经济观察网': 0.85,
  '证券时报': 0.85,
  // 知名科技媒体（权重0.8）
  'Ars Technica': 0.8,
  'Bloomberg Technology': 0.8,
  'EE Times': 0.8,
  'Engadget': 0.8,
  'Financial Times Tech': 0.8,
  'GitHub Trending Go': 0.8,
  'GitHub Trending JS': 0.8,
  'GitHub Trending Python': 0.8,
  'GitHub Trending Rust': 0.8,
  'GitHub Trending TypeScript': 0.8,
  'MarketWatch': 0.8,
  'Reuters Business': 0.8,
  'Reuters Legal': 0.8,
  'Smashing Magazine': 0.8,
  'Stat News': 0.8,
  'Steam News': 0.8,
  'TechCrunch': 0.8,
  'The Hacker News': 0.8,
  'The Verge': 0.8,
  'Wired': 0.8,
  "Barron's": 0.8,
  '东方财富': 0.8,
  '中国新闻网财经': 0.8,
  '人民网财经': 0.8,
  // 标准优质源（权重0.75）
  'AnandTech': 0.75,
  'Anime News Network': 0.75,
  'Ars Technica Gaming': 0.75,
  'BBC Entertainment': 0.75,
  'Canary Media': 0.75,
  'Cointelegraph': 0.75,
  'CoolShell': 0.75,
  'Crunchyroll News': 0.75,
  'Dark Reading': 0.75,
  'Dev.to': 0.75,
  'EdSurge': 0.75,
  'FierceBiotech': 0.75,
  'Futurism': 0.75,
  'HealthTech': 0.75,
  'Hollywood Reporter': 0.75,
  'Investing.com': 0.75,
  'IoT World Today': 0.75,
  'KDnuggets': 0.75,
  'Kiplinger': 0.75,
  'Law.com': 0.75,
  'Legaltech News': 0.75,
  'Lobsters': 0.75,
  'MedTech': 0.75,
  'Medscape': 0.75,
  'Motley Fool': 0.75,
  'PC Gamer': 0.75,
  'Product Hunt Daily': 0.75,
  'Quantum Computing Report': 0.75,
  'Rolling Stone': 0.75,
  'SingularityHub': 0.75,
  'Slashdot': 0.75,
  'Space.com': 0.75,
  'SpaceNews': 0.75,
  'TechCrunch Robotics': 0.75,
  'TechRadar': 0.75,
  'The Block': 0.75,
  'The Guardian Film': 0.75,
  'The Verge Automotive': 0.75,
  "Tom's Hardware": 0.75,
  'Towards Data Science': 0.75,
  'Variety': 0.75,
  'VentureBeat': 0.75,
  '北大法宝': 0.75,
  '机器之心': 0.75,
  '法制日报': 0.75,
  '量子位': 0.75,
  '雪球': 0.75,
  // 标准源（权重0.7）
  '36氪': 0.7,
  '36氪医疗': 0.7,
  'AWS Blog': 0.7,
  'CleanTechnica': 0.7,
  'Electrek': 0.7,
  'Gizmodo': 0.7,
  'Google Cloud Blog': 0.7,
  'Green Car Reports': 0.7,
  'IBM Cloud Blog': 0.7,
  'InfoQ CN': 0.7,
  'Light Reading': 0.7,
  'Microsoft Azure Blog': 0.7,
  'MyAnimeList': 0.7,
  'Nintendo Life': 0.7,
  'Popular Mechanics': 0.7,
  'Rock Paper Shotgun': 0.7,
  'TechCrunch Education': 0.7,
  'TechCrunch Gaming': 0.7,
  'V2EX 技术': 0.7,
  '丁香园': 0.7,
  '健康界': 0.7,
  '医学界': 0.7,
  '知乎AI': 0.7,
  '知乎热榜': 0.7,
  '知乎科技互联网': 0.7,
  '虎嗅': 0.7,
  '钛媒体': 0.7,
  // 基础源（权重0.65）
  'CNET': 0.65,
  'ComicBook.com': 0.65,
  'Segmentfault 热榜': 0.65,
  'TMZ': 0.65,
  'ZDNet': 0.65,
  '少数派': 0.65,
  '微博热搜AI': 0.65,
  '微博热搜科技': 0.65,
  '掘金热榜': 0.65,
  '爱范儿': 0.65,
  // 基础信息源（权重0.6）
  'CSDN 热榜': 0.6,
  'IT之家': 0.6,
  // ========== AIHOT 聚合精选 ==========
  'AIHOT 精选摘要': 1.0,
  'AIHOT 全部 AI 动态': 0.95,
  'Simon Willison 博客': 1.0,
  // ========== 新增 AI 大厂官方 ==========
  'Cohere Blog': 1.0,
  'Mistral AI News': 1.0,
  'Stability AI Blog': 0.95,
  // ========== 新增知名 AI 博主 ==========
  'Lilian Weng': 0.95,
  'Chip Huyen': 0.95,
  'Eugene Yan': 0.95,
  'Sebastian Raschka': 0.95,
  // ========== 新增论文发现平台 ==========
  'Papers with Code': 0.95,
  'Hugging Face Daily Papers': 0.95,
  // ========== 新增国内 AI 权威源 ==========
  '新智元': 0.85,
  'AI 前线': 0.85,
  'PaperWeekly': 0.85,
  // ========== 新增国内大厂技术博客 ==========
  '美团技术团队': 0.95,
  '字节跳动技术': 0.9,
  '阿里云开发者': 0.85,
  '腾讯云开发者': 0.85,
  '华为云开发者': 0.85,
  '滴滴技术团队': 0.85,
  '携程技术': 0.8,
  '哔哩哔哩技术': 0.85,
  '小米开发者': 0.8,
  '京东技术': 0.8,
  '蚂蚁集团技术': 0.85,
  '网易严选技术': 0.75,
  // ========== 新增国内知名博主 ==========
  '阮一峰博客': 0.95,
  '酷壳 CoolShell': 0.9,
  '张鑫旭博客': 0.85,
  '苏剑林博客': 0.9,
  '廖雪峰博客': 0.85,
  'The Decoder': 0.85,
  'TechCrunch AI': 0.85,
  'OpenRouter 公告': 0.95,
  'Midjourney 更新': 0.95,
  // ========== P0 新增：国际标准/监管机构官方 ==========
  'ISO News': 1.0,
  'IEC News': 1.0,
  'IEEE Standards': 1.0,
  'OECD Science': 1.0,
  'EU AI Office': 1.0,
  'White House OSTP': 1.0,
  // ========== P0 新增：中国官方权威机构 ==========
  '国务院新闻办': 1.0,
  '国家发改委': 1.0,
  '国家网信办': 1.0,
  '国家标准化管理委员会': 1.0,
  '中国科学院': 1.0,
  '中国工程院': 1.0,
  '中国科协': 1.0,
  '国家人工智能标椎总体组': 1.0,
  '中国人工智能学会 CAAI': 0.95,
  '中国计算机学会 CCF': 0.95,
  '智源研究院 BAAI': 0.95,
  '之江实验室': 0.95,
  '上海人工智能实验室': 0.95,
  // ========== P0 新增：海外AI独角兽/厂商官方 ==========
  'xAI Blog': 1.0,
  'Groq Blog': 1.0,
  'Databricks Blog': 0.95,
  'Perplexity Blog': 0.95,
  'Character.AI News': 0.95,
  'Inflection AI News': 0.95,
  'Replicate Blog': 0.95,
  'Together AI Blog': 0.95,
  'Fireworks AI Blog': 0.95,
  'Modal Blog': 0.9,
  'Cerebras Blog': 0.95,
  'Tenstorrent Blog': 0.95,
  // ========== P0 新增：国内AI大厂/实验室官方 ==========
  '百度研究院': 1.0,
  '飞桨 PaddlePaddle': 0.95,
  '阿里达摩院': 1.0,
  '通义实验室': 0.95,
  '火山引擎 AI': 0.95,
  '腾讯混元': 0.95,
  '腾讯优图实验室': 0.95,
  '华为诺亚方舟实验室': 0.95,
  '昇腾社区': 0.95,
  '讯飞研究院': 0.95,
  '商汤 SenseTime': 0.95,
  '旷视 Megvii': 0.9,
  'MiniMax 稀宇': 0.95,
  '阶跃星辰 StepFun': 0.95,
  '零一万物': 0.95,
  '月之暗面 Moonshot': 0.95,
  '百川智能 Baichuan': 0.95,
  '深言科技 DeepLang': 0.9,
  // ========== P1 新增：产业联盟/专业媒体 ==========
  'AI Alliance': 0.95,
  'Partnership on AI': 0.95,
  'SemiAnalysis': 0.9,
  'The Next Platform': 0.85,
  'WikiChip Fuse': 0.85,
  '半导体行业观察': 0.85,
  'CNCF Blog': 0.9,
  'Kubernetes Blog': 0.9,
  'Terraform Blog': 0.9,
  'CB Insights Research': 0.9,
  'PitchBook News': 0.85,
  'a16z AI & Tech': 0.95,
  'Sequoia Capital Blog': 0.95,
};;

// ========== 信息源评级系统 ==========
// 来源类型枚举（10大类）
export const SOURCE_TYPES = {
  OFFICIAL_REGULATOR: 'official_regulator',   // 官方监管/标准机构（SS/S级首选）
  OFFICIAL_RESEARCH: 'official_research',     // 官方研究机构/实验室
  VENDOR_OFFICIAL: 'vendor_official',         // AI厂商/科技公司官方博客
  INDUSTRY_ASSOC: 'industry_association',     // 行业协会/产业联盟
  ACADEMIC: 'academic_journal',               // 学术期刊/顶会
  EXPERT_BLOGGER: 'expert_blogger',           // 专家个人博客/专栏（KOL）
  PROFESSIONAL_MEDIA: 'professional_media',   // 专业行业媒体
  TECH_MEDIA: 'tech_media',                   // 大众科技媒体
  DEV_COMMUNITY: 'developer_community',       // 开发者社区
  AGGREGATION: 'aggregation_platform',        // 聚合平台（RSSHub等）
};

// 来源类型元信息（minGrade为该类型允许的最低等级）
export const SOURCE_TYPE_META = {
  official_regulator:   { label: '官方监管机构', iconKey: 'sourceRegulator', minGrade: 'S' },
  official_research:    { label: '官方研究机构', iconKey: 'sourceResearch', minGrade: 'A' },
  vendor_official:      { label: '厂商官方',     iconKey: 'sourceVendor', minGrade: 'A' },
  industry_association: { label: '行业协会',     iconKey: 'sourceAssociation', minGrade: 'B' },
  academic_journal:     { label: '学术期刊',     iconKey: 'sourceAcademic', minGrade: 'A' },
  expert_blogger:       { label: '专家KOL',      iconKey: 'sourceExpert', minGrade: 'B' },
  professional_media:   { label: '专业行业媒体', iconKey: 'sourceProMedia', minGrade: 'B' },
  tech_media:           { label: '大众科技媒体', iconKey: 'sourceTechMedia', minGrade: 'C' },
  developer_community:  { label: '开发者社区',   iconKey: 'sourceDev', minGrade: 'C' },
  aggregation_platform: { label: '聚合平台',     iconKey: 'sourceAgg', minGrade: 'D' },
};

// AI领域二级子类目（后续用于更细粒度筛选）
export const AI_SUBDOMAINS = {
  'llm-foundation':  { label: '大模型基础',   parent: 'ai-models' },
  'llm-application': { label: '大模型应用/Agent', parent: 'ai-models' },
  'computer-vision': { label: '计算机视觉',   parent: 'ai-models' },
  'nlp-speech':      { label: 'NLP/语音',     parent: 'ai-models' },
  'ml-theory':       { label: '机器学习理论', parent: 'research' },
  'ai-policy':       { label: 'AI政策/监管',  parent: 'policy-finance' },
  'ai-safety':       { label: 'AI安全/对齐',  parent: 'cybersecurity' },
  'ai-infra':        { label: 'AI基础设施',   parent: 'cloud' },
};

// 快速筛选档位（前端Chip用）
export const GRADE_PRESET_TIERS = {
  'ss-s':  { label: 'SS+S 权威档', grades: ['S'], iconKey: 'tierSS' },
  'ap-a':  { label: 'A+A 顶级档', grades: ['A'], iconKey: 'tierA' },
  'b':     { label: 'B 优质档',   grades: ['B'], iconKey: 'tierB' },
  'c-d':   { label: 'C+D 基础档', grades: ['C', 'D'], iconKey: 'tierC' },
};

export const REGION_PRESETS = {
  'global':    { label: '全部',   regions: ['domestic', 'overseas', 'global'], iconKey: 'regionGlobal' },
  'domestic':  { label: '国内',   regions: ['domestic'], iconKey: 'regionDomestic' },
  'overseas':  { label: '海外',   regions: ['overseas', 'global'], iconKey: 'regionOversea' },
};

// 权重分级与等级映射
export const SOURCE_GRADES = {
  'S': { weight: 1.0, label: 'S级-权威官方', description: '政府机构、顶级学术期刊、官方博客', color: '#dc2626', iconKey: 'tierS' },
  'A': { weight: 0.95, label: 'A级-顶级源', description: '顶级研究机构、权威财经媒体', color: '#ea580c', iconKey: 'tierA' },
  'B': { weight: 0.85, label: 'B级-优质源', description: '知名科技媒体、专业行业媒体', color: '#16a34a', iconKey: 'tierB' },
  'C': { weight: 0.75, label: 'C级-标准源', description: '一般媒体、开发者社区', color: '#2563eb', iconKey: 'tierC' },
  'D': { weight: 0.65, label: 'D级-基础源', description: 'RSSHub聚合、一般源', color: '#64748b', iconKey: 'tierD' }
};

// 信息源等级映射（按名称到等级）
export const SOURCE_GRADE_MAP = {
  // S级 - 权威官方（政府机构、顶级期刊、顶级实验室、AI官方博客）
  'Amazon AI Blog': 'S',
  'Amazon Science': 'S',
  'Anthropic News': 'S',
  'Apple Machine Learning': 'S',
  'Bloomberg Markets': 'S',
  'CMU RI': 'S',
  'CNBC Markets': 'S',
  'DARPA News': 'S',
  'Financial Times Markets': 'S',
  'Google AI Blog': 'S',
  'Google DeepMind': 'S',
  'Google Research Blog': 'S',
  'IBM Research': 'S',
  'MIT CSAIL': 'S',
  'Meta AI Blog': 'S',
  'Meta AI Research (FAIR)': 'S',
  'Microsoft AI Blog': 'S',
  'Microsoft Research': 'S',
  'Microsoft Research AI': 'S',
  'NIST Technology': 'S',
  'NVIDIA AI Blog': 'S',
  'X @OpenAI': 'S',
  'X @AnthropicAI': 'S',
  'X @GoogleDeepMind': 'S',
  'X @NVIDIA': 'S',
  'X @ylecun': 'A',
  'X @demishassabis': 'A',
  'YouTube @OpenAI': 'S',
  'YouTube @DeepMind': 'S',
  'YouTube @TwoMinutePapers': 'A',
  'YouTube @YannLeCun': 'A',
  'Nature': 'S',
  'Nature Biotechnology': 'S',
  'Nature Machine Intelligence': 'S',
  'Nature Medicine': 'S',
  'OpenAI Blog': 'S',
  'Reuters Finance': 'S',
  'Science Advances': 'S',
  'Science Magazine': 'S',
  'Stanford HAI': 'S',
  'Stanford SAIL': 'S',
  'UC Berkeley BAIR': 'S',
  'Wall Street Journal': 'S',
  '中国法院网': 'S',
  '工信部': 'S',
  '科技部': 'S',
  // A级 - 顶级源（权威财经媒体、顶级研究、开发者社区）
  'ACM TechNews': 'A',
  'ArXiv CS AI': 'A',
  'ArXiv CS CL': 'A',
  'ArXiv CS CV': 'A',
  'ArXiv CS ML': 'A',
  'ArXiv CS NE': 'A',
  'ArXiv CS RO': 'A',
  'ArXiv Quantitative Finance': 'A',
  'GitHub Blog': 'A',
  'GitHub Engineering': 'A',
  'Hacker News': 'A',
  'Hacker News Best': 'A',
  'IEEE Spectrum': 'A',
  "Barron's": 'A',
  'Investing.com': 'A',
  'Kiplinger': 'A',
  'MIT News AI': 'A',
  'MIT News Tech': 'A',
  'MarketWatch': 'A',
  'Science Daily': 'A',
  'Seeking Alpha': 'A',
  '中国证券报': 'A',
  '华尔街见闻': 'A',
  '第一财经': 'A',
  '证券时报': 'A',
  '财新网': 'A',
  // B级 - 优质源（知名媒体、专业平台、专业行业媒体）
  '36氪': 'B',
  'AWS Blog': 'B',
  'AnandTech': 'B',
  'Ars Technica': 'B',
  'BBC Entertainment': 'B',
  'Canary Media': 'B',
  'EE Times': 'B',
  'FierceBiotech': 'B',
  'Google Cloud Blog': 'B',
  'Hollywood Reporter': 'B',
  'IBM Cloud Blog': 'B',
  'InfoQ CN': 'B',
  'KrebsOnSecurity': 'B',
  'MIT Technology Review': 'B',
  'Microsoft Azure Blog': 'B',
  'Quanta Magazine': 'B',
  'Rolling Stone': 'B',
  'Semiconductor Engineering': 'B',
  'Stat News': 'B',
  'TechCrunch': 'B',
  'The Guardian Film': 'B',
  'The Hacker News': 'B',
  'The Verge': 'B',
  'Variety': 'B',
  'VentureBeat': 'B',
  'Wired': 'B',
  "Tom's Hardware": 'B',
  '机器之心': 'B',
  '虎嗅': 'B',
  '量子位': 'B',
  '钛媒体': 'B',
  // C级 - 标准源（一般媒体、开发者社区、专业评测）
  '36氪医疗': 'C',
  'Anime News Network': 'C',
  'Ars Technica Gaming': 'C',
  'CNET': 'C',
  'CleanTechnica': 'C',
  'Cointelegraph': 'C',
  'ComicBook.com': 'C',
  'CoolShell': 'C',
  'Crunchyroll News': 'C',
  'Dark Reading': 'C',
  'Dev.to': 'C',
  'EdSurge': 'C',
  'Electrek': 'C',
  'Engadget': 'C',
  'Gizmodo': 'C',
  'Green Car Reports': 'C',
  'HealthTech': 'C',
  'IT之家': 'C',
  'IoT World Today': 'C',
  'KDnuggets': 'C',
  'Law.com': 'C',
  'Legaltech News': 'C',
  'Light Reading': 'C',
  'Lobsters': 'C',
  'MedTech': 'C',
  'Medscape': 'C',
  'Motley Fool': 'C',
  'MyAnimeList': 'C',
  'Nintendo Life': 'C',
  'OSChina': 'C',
  'PC Gamer': 'C',
  'Popular Mechanics': 'C',
  'Quantum Computing Report': 'C',
  'Reuters Legal': 'C',
  'Rock Paper Shotgun': 'C',
  'Slashdot': 'C',
  'Smashing Magazine': 'C',
  'Solidot': 'C',
  'Space.com': 'C',
  'SpaceNews': 'C',
  'Steam News': 'C',
  'TechCrunch Education': 'C',
  'TechCrunch Gaming': 'C',
  'TechCrunch Robotics': 'C',
  'TechRadar': 'C',
  'The Block': 'C',
  'The Verge Automotive': 'C',
  'Towards Data Science': 'C',
  'ZDNet': 'C',
  '丁香园': 'C',
  '东方财富': 'C',
  '健康界': 'C',
  '北大法宝': 'C',
  '医学界': 'C',
  '少数派': 'C',
  '爱范儿': 'C',
  '经济观察网': 'C',
  '雪球': 'C',
  // D级 - 基础源（RSSHub聚合、一般源）
  'CSDN 热榜': 'D',
  'GitHub Trending Go': 'D',
  'GitHub Trending JS': 'D',
  'GitHub Trending Python': 'D',
  'GitHub Trending Rust': 'D',
  'GitHub Trending TypeScript': 'D',
  'Hugging Face Blog': 'A',
  'Product Hunt Daily': 'D',
  'Reddit MachineLearning': 'D',
  'Reddit Technology': 'D',
  'Segmentfault 热榜': 'D',
  'TMZ': 'D',
  'V2EX 技术': 'D',
  '中国新闻网': 'D',
  '中国新闻网财经': 'D',
  '人民网财经': 'D',
  '微博热搜AI': 'D',
  '微博热搜科技': 'D',
  '掘金热榜': 'D',
  '知乎AI': 'D',
  '知乎热榜': 'D',
  '知乎科技互联网': 'D',
  // ========== AIHOT 聚合精选 ==========
  'AIHOT 精选摘要': 'S',
  'AIHOT 全部 AI 动态': 'S',
  'Simon Willison 博客': 'S',
  // ========== 新增 AI 大厂官方 ==========
  'Cohere Blog': 'S',
  'Mistral AI News': 'S',
  'Stability AI Blog': 'A',
  // ========== 新增知名 AI 博主 ==========
  'Lilian Weng': 'A',
  'Chip Huyen': 'A',
  'Eugene Yan': 'A',
  'Sebastian Raschka': 'A',
  // ========== 新增论文发现平台 ==========
  'Papers with Code': 'A',
  'Hugging Face Daily Papers': 'A',
  // ========== 新增国内 AI 权威源 ==========
  '新智元': 'B',
  'AI 前线': 'B',
  'PaperWeekly': 'B',
  // ========== 新增国内大厂技术博客 ==========
  '美团技术团队': 'A',
  '字节跳动技术': 'B',
  '阿里云开发者': 'B',
  '腾讯云开发者': 'B',
  '华为云开发者': 'B',
  '滴滴技术团队': 'B',
  '携程技术': 'B',
  '哔哩哔哩技术': 'B',
  '小米开发者': 'B',
  '京东技术': 'B',
  '蚂蚁集团技术': 'B',
  '网易严选技术': 'C',
  // ========== 新增国内知名博主 ==========
  '阮一峰博客': 'A',
  '酷壳 CoolShell': 'B',
  '张鑫旭博客': 'B',
  '苏剑林博客': 'A',
  '廖雪峰博客': 'B',
  'The Decoder': 'B',
  'TechCrunch AI': 'B',
  'OpenRouter 公告': 'A',
  'Midjourney 更新': 'A',
  // ========== P0 新增：国际标准/监管机构官方 ==========
  'ISO News': 'S',
  'IEC News': 'S',
  'IEEE Standards': 'S',
  'OECD Science': 'S',
  'EU AI Office': 'S',
  'White House OSTP': 'S',
  // ========== P0 新增：中国官方权威机构 ==========
  '国务院新闻办': 'S',
  '国家发改委': 'S',
  '国家网信办': 'S',
  '国家标准化管理委员会': 'S',
  '中国科学院': 'S',
  '中国工程院': 'S',
  '中国科协': 'S',
  '国家人工智能标椎总体组': 'S',
  '中国人工智能学会 CAAI': 'A',
  '中国计算机学会 CCF': 'A',
  '智源研究院 BAAI': 'A',
  '之江实验室': 'A',
  '上海人工智能实验室': 'A',
  // ========== P0 新增：海外AI独角兽/厂商官方 ==========
  'xAI Blog': 'S',
  'Groq Blog': 'S',
  'Databricks Blog': 'A',
  'Perplexity Blog': 'A',
  'Character.AI News': 'A',
  'Inflection AI News': 'A',
  'Replicate Blog': 'A',
  'Together AI Blog': 'A',
  'Fireworks AI Blog': 'A',
  'Modal Blog': 'A',
  'Cerebras Blog': 'A',
  'Tenstorrent Blog': 'A',
  // ========== P0 新增：国内AI大厂/实验室官方 ==========
  '百度研究院': 'S',
  '飞桨 PaddlePaddle': 'A',
  '阿里达摩院': 'S',
  '通义实验室': 'A',
  '火山引擎 AI': 'A',
  '腾讯混元': 'A',
  '腾讯优图实验室': 'A',
  '华为诺亚方舟实验室': 'A',
  '昇腾社区': 'A',
  '讯飞研究院': 'A',
  '商汤 SenseTime': 'A',
  '旷视 Megvii': 'A',
  'MiniMax 稀宇': 'A',
  '阶跃星辰 StepFun': 'A',
  '零一万物': 'A',
  '月之暗面 Moonshot': 'A',
  '百川智能 Baichuan': 'A',
  '深言科技 DeepLang': 'A',
  // ========== P1 新增：产业联盟/专业媒体 ==========
  'AI Alliance': 'A',
  'Partnership on AI': 'A',
  'SemiAnalysis': 'A',
  'The Next Platform': 'B',
  'WikiChip Fuse': 'B',
  '半导体行业观察': 'B',
  'CNCF Blog': 'A',
  'Kubernetes Blog': 'A',
  'Terraform Blog': 'A',
  'CB Insights Research': 'A',
  'PitchBook News': 'B',
  'a16z AI & Tech': 'A',
  'Sequoia Capital Blog': 'A',
  // ========== 本轮新增高质量源等级 ==========
  'PNAS': 'S',
  'JMLR': 'A',
  'Joel on Software': 'A',
  'Coding Horror': 'B',
  'Benedict Evans': 'A',
  'Paul Graham Essays': 'A',
  '池建强 MacTalk': 'B',
  '极客公园': 'B',
  '雷锋网': 'B',
  '博客园': 'B',
  'FreeBuf': 'B',
};;

// 多源交叉验证阈值：同一URL在多少个源出现才算高可信度
export const CROSS_VERIFY_THRESHOLD = 3;

export const MAX_NEWS_ITEMS = 500;
export const MAX_ITEMS_PER_SOURCE = 16;
export const PAGE_SIZE = 40;

// 公共RSSHub实例随网络环境波动较大；本地部署推荐自建或用备选实例。
// 这里预留3个公共节点串联模板，实际抓取时可在 settings -> LLM&源设置 -> 自定义源 处切换。
export const RSSHUB_BASE = 'https://rsshub.rssforever.com';
export const RSSHUB_FALLBACKS = [
  'https://rsshub.rssforever.com',
  'https://rsshub.app',
  'https://rss.inshs.xyz',
];
// 通用 fallback：对没有原生RSS的官网，用 simple-sitemap-parser 抓首页链接生成伪RSS。
// 注意：simple-sitemap-parser 要求 RSSHub 实例版本 >= 2024.x；参数 url = 目标官网首页。
const SITEMAP_PARSER = (url) => `${RSSHUB_BASE}/simple-sitemap-parser?url=${encodeURIComponent(url)}&sitemap=false`;

export const DEFAULT_SOURCES = [
  // ========== 学术权威与研究 ==========
  { name: 'Nature', url: 'https://www.nature.com/nature.rss', region: 'global', defaultCategory: 'research' },
  { name: 'Science Magazine', url: 'https://www.science.org/rss/news_current.xml', region: 'global', defaultCategory: 'research' },
  { name: 'Nature Machine Intelligence', url: 'https://www.nature.com/natmachintell.rss', region: 'global', defaultCategory: 'research' },
  { name: 'ArXiv CS AI', url: 'https://export.arxiv.org/rss/cs.AI', region: 'global', defaultCategory: 'research' },
  { name: 'ArXiv CS ML', url: 'https://export.arxiv.org/rss/cs.LG', region: 'global', defaultCategory: 'research' },
  { name: 'ArXiv CS CL', url: 'https://export.arxiv.org/rss/cs.CL', region: 'global', defaultCategory: 'research' },
  { name: 'ArXiv CS CV', url: 'https://export.arxiv.org/rss/cs.CV', region: 'global', defaultCategory: 'research' },
  { name: 'MIT News AI', url: 'https://news.mit.edu/rss/topic/artificial-intelligence2', region: 'overseas', defaultCategory: 'research' },
  { name: 'Stanford HAI', url: 'https://hai.stanford.edu/news/rss.xml', region: 'overseas', defaultCategory: 'research' },
  { name: 'Science Daily', url: 'https://www.sciencedaily.com/rss/', region: 'overseas', defaultCategory: 'research' },
  { name: 'IEEE Spectrum', url: 'https://spectrum.ieee.org/rss/fulltext', region: 'overseas', defaultCategory: 'research' },
  { name: 'MIT Technology Review', url: 'https://www.technologyreview.com/feed/', region: 'overseas', defaultCategory: 'research' },
  { name: 'Quanta Magazine', url: 'https://www.quantamagazine.org/feed/', region: 'overseas', defaultCategory: 'research' },
  { name: 'Nature Medicine', url: 'https://www.nature.com/nm.rss', region: 'global', defaultCategory: 'research' },
  { name: 'MIT CSAIL', url: 'https://www.csail.mit.edu/news/feed', region: 'overseas', defaultCategory: 'research' },
  { name: 'Stanford SAIL', url: 'https://ai.stanford.edu/news/feed', region: 'overseas', defaultCategory: 'research' },
  { name: 'UC Berkeley BAIR', url: 'https://bair.berkeley.edu/blog/feed.xml', region: 'overseas', defaultCategory: 'research' },
  { name: 'CMU RI', url: 'https://www.ri.cmu.edu/news/feed/', region: 'overseas', defaultCategory: 'research' },
  { name: 'Google Research Blog', url: 'https://blog.google/technology/research/', region: 'overseas', defaultCategory: 'research' },
  { name: 'Microsoft Research', url: 'https://www.microsoft.com/en-us/research/blog/feed/', region: 'overseas', defaultCategory: 'research' },
  { name: 'IBM Research', url: 'https://www.ibm.com/research/feed', region: 'overseas', defaultCategory: 'research' },
  { name: 'Meta AI Research (FAIR)', url: 'https://ai.facebook.com/blog/feed/', region: 'overseas', defaultCategory: 'research' },
  { name: 'Amazon Science', url: 'https://www.amazon.science/feed', region: 'overseas', defaultCategory: 'research' },
  { name: 'DARPA News', url: 'https://www.darpa.mil/news-events/feed', region: 'overseas', defaultCategory: 'research' },
  { name: 'Nature Biotechnology', url: 'https://www.nature.com/nbt.rss', region: 'global', defaultCategory: 'research' },
  { name: 'Science Advances', url: 'https://www.science.org/rss/advance.xml', region: 'global', defaultCategory: 'research' },
  { name: 'ArXiv CS RO', url: 'https://export.arxiv.org/rss/cs.RO', region: 'global', defaultCategory: 'research' },
  { name: 'ArXiv CS NE', url: 'https://export.arxiv.org/rss/cs.NE', region: 'global', defaultCategory: 'research' },
  // ========== 新增：论文发现平台 ==========
  { name: 'Papers with Code', url: 'https://paperswithcode.com/latest.rss', region: 'global', defaultCategory: 'research' },
  { name: 'Hugging Face Daily Papers', url: 'https://huggingface.co/papers/feed', region: 'global', defaultCategory: 'research' },
  { name: 'MIT News Tech', url: 'https://news.mit.edu/rss/topic/technology', region: 'overseas', defaultCategory: 'research' },
  { name: 'ACM TechNews', url: 'https://technews.acm.org/rss', region: 'overseas', defaultCategory: 'research' },
  // ========== 新增：学术顶刊（高质量一手研究） ==========
  { name: 'PNAS', url: 'https://www.pnas.org/action/showFeed?type=etoc&feed=rss&jc=pnas', region: 'global', defaultCategory: 'research', sourceType: 'academic_journal', tags: ['学术','PNAS','顶刊'] },
  { name: 'JMLR', url: 'http://jmlr.org/jmlr.xml', region: 'global', defaultCategory: 'research', sourceType: 'academic_journal', tags: ['学术','JMLR','机器学习'] },
  // ========== AI/大模型官方博客（一手信息） ==========
  { name: 'OpenAI Blog', url: 'https://openai.com/blog/rss.xml', region: 'overseas', defaultCategory: 'ai-models' },
  { name: 'Anthropic News', url: 'https://www.anthropic.com/news/rss', region: 'overseas', defaultCategory: 'ai-models' },
  { name: 'Google DeepMind', url: 'https://deepmind.google/blog/rss.xml', region: 'overseas', defaultCategory: 'ai-models' },
  { name: 'Meta AI Blog', url: 'https://ai.meta.com/blog/rss/', region: 'overseas', defaultCategory: 'ai-models' },
  { name: 'Google AI Blog', url: 'https://blog.google/technology/ai/rss/', region: 'overseas', defaultCategory: 'ai-models' },
  { name: 'Microsoft AI Blog', url: 'https://blogs.microsoft.com/ai/feed/', region: 'overseas', defaultCategory: 'ai-models' },
  { name: 'Apple Machine Learning', url: 'https://machinelearning.apple.com/rss.xml', region: 'overseas', defaultCategory: 'ai-models' },
  { name: 'Hugging Face Blog', url: 'https://huggingface.co/blog/feed.xml', region: 'global', defaultCategory: 'ai-models' },
  { name: 'AI News', url: 'https://www.artificialintelligence-news.com/feed/', region: 'overseas', defaultCategory: 'ai-models' },
  { name: 'Reddit MachineLearning', url: 'https://www.reddit.com/r/MachineLearning/.rss', region: 'global', defaultCategory: 'ai-models' },
  { name: '量子位', url: 'https://www.qbitai.com/feed', region: 'domestic', defaultCategory: 'ai-models' },
  { name: '机器之心', url: 'https://www.jiqizhixin.com/rss', region: 'domestic', defaultCategory: 'ai-models' },
  // ========== 新增：国内 AI 权威源 ==========
  { name: '新智元', url: 'https://rsshub.rssforever.com/aminer/ai', region: 'domestic', defaultCategory: 'ai-models' },
  { name: 'AI 前线', url: 'https://rsshub.rssforever.com/infoq/ai', region: 'domestic', defaultCategory: 'ai-models' },
  { name: 'PaperWeekly', url: 'https://rsshub.rssforever.com/paperweekly/popular', region: 'domestic', defaultCategory: 'ai-models' },
  // ========== 新增：国内大厂技术博客（多数走 RSSHub 路由） ==========
  { name: '美团技术团队', url: 'https://tech.meituan.com/feed/', region: 'domestic', defaultCategory: 'ai-models' },
  { name: '字节跳动技术', url: 'https://rsshub.rssforever.com/juejin/posts/1838039172387262', region: 'domestic', defaultCategory: 'ai-models' },
  { name: '阿里云开发者', url: 'https://rsshub.rssforever.com/aliyun/field/11', region: 'domestic', defaultCategory: 'ai-models' },
  { name: '腾讯云开发者', url: 'https://rsshub.rssforever.com/tencent/cloud/developer', region: 'domestic', defaultCategory: 'ai-models' },
  { name: '华为云开发者', url: 'https://rsshub.rssforever.com/huaweicloud/developer', region: 'domestic', defaultCategory: 'ai-models' },
  { name: '滴滴技术团队', url: 'https://didi.github.io/atom.xml', region: 'domestic', defaultCategory: 'ai-models' },
  { name: '携程技术', url: 'https://rsshub.rssforever.com/ctrip/tech', region: 'domestic', defaultCategory: 'ai-models' },
  { name: '哔哩哔哩技术', url: 'https://rsshub.rssforever.com/bilibili/search/article/技术', region: 'domestic', defaultCategory: 'ai-models' },
  { name: '小米开发者', url: 'https://rsshub.rssforever.com/xiaomi/dev', region: 'domestic', defaultCategory: 'ai-models' },
  { name: '京东技术', url: 'https://developer.jd.com/article/feed', region: 'domestic', defaultCategory: 'ai-models' },
  { name: '蚂蚁集团技术', url: 'https://rsshub.rssforever.com/antfin/tech', region: 'domestic', defaultCategory: 'ai-models' },
  { name: '网易严选技术', url: 'https://rsshub.rssforever.com/you163/tech', region: 'domestic', defaultCategory: 'ai-models' },
  // ========== 新增：国内知名博主 ==========
  { name: '阮一峰博客', url: 'http://www.ruanyifeng.com/blog/atom.xml', region: 'domestic', defaultCategory: 'ai-models' },
  { name: '张鑫旭博客', url: 'https://www.zhangxinxu.com/wordpress/feed/', region: 'domestic', defaultCategory: 'ai-models' },
  { name: '苏剑林博客', url: 'https://kexue.fm/feed.xml', region: 'domestic', defaultCategory: 'ai-models' },
  { name: '廖雪峰博客', url: 'https://www.liaoxuefeng.com/feed/', region: 'domestic', defaultCategory: 'ai-models' },
  { name: '知乎AI', url: 'https://rsshub.rssforever.com/zhihu/topic/19550517', region: 'domestic', defaultCategory: 'ai-models' },
  { name: '微博热搜AI', url: 'https://rsshub.rssforever.com/weibo/search/hot/AI', region: 'domestic', defaultCategory: 'ai-models' },
  // ========== v26.9 新增：国内源（全部经 scripts/test-source-candidates*.mjs 实测通过后接入） ==========
  { name: '有赞技术', url: 'https://tech.youzan.com/feed/', region: 'domestic', defaultCategory: 'ai-models', sourceType: 'company_blog', tags: ['国内','有赞','大厂技术'] },
  { name: '云风博客', url: 'https://blog.codingnow.com/atom.xml', region: 'domestic', defaultCategory: 'open-source', sourceType: 'expert_blogger', tags: ['国内','云风','游戏引擎/编程'] },
  { name: '程序师视野', url: 'https://www.techug.com/feed', region: 'domestic', defaultCategory: 'china-tech', sourceType: 'tech_media', tags: ['国内','程序师','开发者视野'] },
  { name: '稀土掘金 AI', url: 'https://rss.injahow.cn/juejin/tag/人工智能', region: 'domestic', defaultCategory: 'ai-models', sourceType: 'developer_community', tags: ['国内','掘金','AI'] },
  { name: '稀土掘金 前端', url: 'https://rss.injahow.cn/juejin/tag/前端', region: 'domestic', defaultCategory: 'open-source', sourceType: 'developer_community', tags: ['国内','掘金','前端'] },
  { name: '稀土掘金 后端', url: 'https://rss.injahow.cn/juejin/tag/后端', region: 'domestic', defaultCategory: 'open-source', sourceType: 'developer_community', tags: ['国内','掘金','后端'] },
  { name: 'Microsoft Research AI', url: 'https://www.microsoft.com/en-us/research/blog/topic/artificial-intelligence/feed/', region: 'overseas', defaultCategory: 'ai-models' },
  { name: 'NVIDIA AI Blog', url: 'https://blogs.nvidia.com/feed/', region: 'overseas', defaultCategory: 'ai-models' },
  { name: 'Amazon AI Blog', url: 'https://aws.amazon.com/blogs/machine-learning/feed/', region: 'overseas', defaultCategory: 'ai-models' },
  // ========== AIHOT 聚合精选及新增高质量源 ==========
  { name: 'AIHOT 精选摘要', url: 'https://aihot.virxact.com/feed.xml', region: 'global', defaultCategory: 'ai-models' },
  { name: 'AIHOT 全部 AI 动态', url: 'https://aihot.virxact.com/feed/all.xml', region: 'global', defaultCategory: 'ai-models' },
  { name: 'Simon Willison 博客', url: 'https://simonwillison.net/atom/everything/', region: 'global', defaultCategory: 'ai-models' },
  { name: 'The Decoder', url: 'https://the-decoder.com/feed/', region: 'overseas', defaultCategory: 'ai-models' },
  { name: 'TechCrunch AI', url: 'https://techcrunch.com/category/artificial-intelligence/feed/', region: 'overseas', defaultCategory: 'ai-models' },
  { name: 'OpenRouter 公告', url: 'https://openrouter.ai/blog/feed.xml', region: 'overseas', defaultCategory: 'ai-models' },
  { name: 'Midjourney 更新', url: 'https://updates.midjourney.com/rss/', region: 'overseas', defaultCategory: 'ai-models' },
  // ========== 新增：AI 大厂官方博客（补全覆盖盲区） ==========
  { name: 'Cohere Blog', url: 'https://cohere.com/blog/rss.xml', region: 'overseas', defaultCategory: 'ai-models' },
  { name: 'Mistral AI News', url: 'https://mistral.ai/news/rss.xml', region: 'overseas', defaultCategory: 'ai-models' },
  { name: 'Stability AI Blog', url: 'https://stability.ai/blog/atom.xml', region: 'overseas', defaultCategory: 'ai-models' },
  // ========== 新增：知名 AI 博主（一手思想源） ==========
  { name: 'Lilian Weng', url: 'https://lilianweng.github.io/index.xml', region: 'overseas', defaultCategory: 'ai-models' },
  { name: 'Chip Huyen', url: 'https://huyenchip.com/feed.xml', region: 'overseas', defaultCategory: 'ai-models' },
  { name: 'Eugene Yan', url: 'https://eugeneyan.com/feed.xml', region: 'overseas', defaultCategory: 'ai-models' },
  { name: 'Sebastian Raschka', url: 'https://magazine.sebastianraschka.com/feed', region: 'overseas', defaultCategory: 'ai-models' },
  // ========== 新增：国际/国内高质量博主（一手思想源） ==========
  { name: 'Joel on Software', url: 'https://www.joelonsoftware.com/feed/', region: 'overseas', defaultCategory: 'open-source', sourceType: 'expert_blogger', tags: ['海外','Joel Spolsky','软件工程'] },
  { name: 'Coding Horror', url: 'https://blog.codinghorror.com/rss/', region: 'overseas', defaultCategory: 'open-source', sourceType: 'expert_blogger', tags: ['海外','Jeff Atwood','编程'] },
  { name: 'Benedict Evans', url: 'https://www.ben-evans.com/benedictevans?format=rss', region: 'overseas', defaultCategory: 'silicon-valley', sourceType: 'expert_blogger', tags: ['海外','Benedict Evans','科技战略'] },
  { name: 'Paul Graham Essays', url: 'http://www.aaronsw.com/2002/feeds/pgessays.rss', region: 'overseas', defaultCategory: 'silicon-valley', sourceType: 'expert_blogger', tags: ['海外','Paul Graham','创业'] },
  { name: '池建强 MacTalk', url: 'https://macshuo.com/?feed=rss2', region: 'domestic', defaultCategory: 'ai-models', sourceType: 'expert_blogger', tags: ['国内','池建强','Mac/iOS'] },
  // ========== 开发者社区与开源 ==========
  { name: 'Hacker News', url: 'https://hnrss.org/frontpage', region: 'global', defaultCategory: 'open-source' },
  { name: 'Hacker News Best', url: 'https://hnrss.org/best', region: 'global', defaultCategory: 'open-source' },
  { name: 'GitHub Blog', url: 'https://github.blog/feed/', region: 'global', defaultCategory: 'open-source' },
  { name: 'GitHub Engineering', url: 'https://githubengineering.com/', region: 'global', defaultCategory: 'open-source' },
  { name: 'Dev.to', url: 'https://dev.to/feed', region: 'global', defaultCategory: 'open-source' },
  { name: 'Smashing Magazine', url: 'https://www.smashingmagazine.com/feed/', region: 'global', defaultCategory: 'open-source' },
  { name: 'Slashdot', url: 'https://rss.slashdot.org/Slashdot/slashdotMain', region: 'overseas', defaultCategory: 'open-source' },
  { name: 'Solidot', url: 'https://www.solidot.org/index.rss', region: 'domestic', defaultCategory: 'open-source' },
  { name: 'OSChina', url: 'https://www.oschina.net/news/rss', region: 'domestic', defaultCategory: 'open-source' },
  { name: 'CoolShell', url: 'https://coolshell.cn/feed', region: 'domestic', defaultCategory: 'open-source' },
  { name: 'GitHub Trending JS', url: 'https://rsshub.rssforever.com/github/trending/daily/javascript', region: 'global', defaultCategory: 'open-source' },
  { name: 'GitHub Trending Python', url: 'https://rsshub.rssforever.com/github/trending/daily/python', region: 'global', defaultCategory: 'open-source' },
  { name: 'GitHub Trending Rust', url: 'https://rsshub.rssforever.com/github/trending/daily/rust', region: 'global', defaultCategory: 'open-source' },
  { name: 'GitHub Trending TypeScript', url: 'https://rsshub.rssforever.com/github/trending/daily/typescript', region: 'global', defaultCategory: 'open-source' },
  { name: 'GitHub Trending Go', url: 'https://rsshub.rssforever.com/github/trending/daily/go', region: 'global', defaultCategory: 'open-source' },
  { name: 'V2EX 技术', url: 'https://rsshub.rssforever.com/v2ex/topics/hot', region: 'domestic', defaultCategory: 'open-source' },
  { name: 'Segmentfault 热榜', url: 'https://rsshub.rssforever.com/segmentfault/hot', region: 'domestic', defaultCategory: 'open-source' },
  { name: '掘金热榜', url: 'https://rsshub.rssforever.com/juejin/trending/javascript/7days', region: 'domestic', defaultCategory: 'open-source' },
  { name: 'CSDN 热榜', url: 'https://rsshub.rssforever.com/csdn/blog/hot', region: 'domestic', defaultCategory: 'open-source' },
  // ========== 国际顶级科技媒体 ==========
  { name: 'TechCrunch', url: 'https://techcrunch.com/feed/', region: 'overseas', defaultCategory: 'silicon-valley' },
  { name: 'Wired', url: 'https://www.wired.com/feed/rss', region: 'overseas', defaultCategory: 'silicon-valley' },
  { name: 'Ars Technica', url: 'https://feeds.arstechnica.com/arstechnica/index', region: 'overseas', defaultCategory: 'silicon-valley' },
  { name: 'VentureBeat', url: 'https://venturebeat.com/feed/', region: 'overseas', defaultCategory: 'silicon-valley' },
  { name: 'ZDNet', url: 'https://www.zdnet.com/news/rss.xml', region: 'overseas', defaultCategory: 'silicon-valley' },
  { name: 'Reddit Technology', url: 'https://www.reddit.com/r/technology/.rss', region: 'global', defaultCategory: 'silicon-valley' },
  { name: 'Product Hunt Daily', url: 'https://rsshub.rssforever.com/producthunt/today', region: 'overseas', defaultCategory: 'silicon-valley' },
  // ========== 硬件数码与专业科技媒体 ==========
  { name: 'The Verge', url: 'https://www.theverge.com/rss/index.xml', region: 'overseas', defaultCategory: 'devices' },
  { name: 'CNET', url: 'https://www.cnet.com/rss/news/', region: 'overseas', defaultCategory: 'devices' },
  { name: 'Engadget', url: 'https://www.engadget.com/rss.xml', region: 'overseas', defaultCategory: 'devices' },
  { name: 'TechRadar', url: 'https://www.techradar.com/rss', region: 'overseas', defaultCategory: 'devices' },
  { name: 'Gizmodo', url: 'https://gizmodo.com/rss', region: 'overseas', defaultCategory: 'devices' },
  { name: '少数派', url: 'https://sspai.com/feed', region: 'domestic', defaultCategory: 'devices' },
  { name: '爱范儿', url: 'https://www.ifanr.com/feed', region: 'domestic', defaultCategory: 'devices' },
  { name: 'PC Gamer', url: 'https://www.pcgamer.com/rss/', region: 'overseas', defaultCategory: 'devices' },
  { name: 'BBC Technology', url: 'https://feeds.bbci.co.uk/news/technology/rss.xml', region: 'overseas', defaultCategory: 'devices' },
  { name: "Tom's Hardware", url: 'https://www.tomshardware.com/feeds/all', region: 'overseas', defaultCategory: 'devices' },
  // ========== 云计算（厂商官方） ==========
  { name: 'AWS Blog', url: 'https://aws.amazon.com/blogs/aws/feed/', region: 'overseas', defaultCategory: 'cloud' },
  { name: 'Google Cloud Blog', url: 'https://cloud.google.com/blog/feed', region: 'overseas', defaultCategory: 'cloud' },
  { name: 'Microsoft Azure Blog', url: 'https://azure.microsoft.com/en-us/blog/feed/', region: 'overseas', defaultCategory: 'cloud' },
  { name: 'IBM Cloud Blog', url: 'https://www.ibm.com/cloud/blog/feed', region: 'overseas', defaultCategory: 'cloud' },
  { name: '腾讯云开发者', url: 'https://cloud.tencent.com/developer/rss', region: 'domestic', defaultCategory: 'cloud' },
  { name: '阿里云开发者', url: 'https://developer.aliyun.com/rss', region: 'domestic', defaultCategory: 'cloud' },
  { name: '华为云开发者', url: 'https://rsshub.rssforever.com/huaweicloud/zh/blog', region: 'domestic', defaultCategory: 'cloud' },
  // ========== 芯片半导体 ==========
  { name: 'AnandTech', url: 'https://www.anandtech.com/rss/newsfeed.aspx', region: 'overseas', defaultCategory: 'chips-compute' },
  { name: 'Semiconductor Engineering', url: 'https://semiengineering.com/feed/', region: 'overseas', defaultCategory: 'chips-compute' },
  { name: 'EE Times', url: 'https://www.eetimes.com/feed/', region: 'overseas', defaultCategory: 'chips-compute' },
  // ========== 网络安全 ==========
  { name: 'KrebsOnSecurity', url: 'https://krebsonsecurity.com/feed/', region: 'overseas', defaultCategory: 'cybersecurity' },
  { name: 'The Hacker News', url: 'https://feeds.feedburner.com/TheHackersNews', region: 'global', defaultCategory: 'cybersecurity' },
  { name: 'Dark Reading', url: 'https://www.darkreading.com/rss.xml', region: 'overseas', defaultCategory: 'cybersecurity' },
  // ========== 机器人 ==========
  { name: 'TechCrunch Robotics', url: 'https://techcrunch.com/category/robotics/feed/', region: 'overseas', defaultCategory: 'robotics' },
  // ========== 前沿科技 ==========
  { name: 'Futurism', url: 'https://futurism.com/feed', region: 'overseas', defaultCategory: 'tech-frontier' },
  { name: 'SingularityHub', url: 'https://singularityhub.com/feed/', region: 'overseas', defaultCategory: 'tech-frontier' },
  { name: '知乎热榜', url: 'https://rsshub.rssforever.com/zhihu/hotlist', region: 'domestic', defaultCategory: 'tech-frontier' },
  { name: '知乎科技互联网', url: 'https://rsshub.rssforever.com/zhihu/topic/19550895', region: 'domestic', defaultCategory: 'tech-frontier' },
  { name: '微博热搜科技', url: 'https://rsshub.rssforever.com/weibo/search/hot/科技', region: 'domestic', defaultCategory: 'tech-frontier' },
  // ========== 新能源 ==========
  { name: 'Canary Media', url: 'https://www.canarymedia.com/feed', region: 'overseas', defaultCategory: 'new-energy' },
  { name: 'Electrek', url: 'https://electrek.co/feed/', region: 'overseas', defaultCategory: 'new-energy' },
  { name: 'Green Car Reports', url: 'https://www.greencarreports.com/news/rss.xml', region: 'overseas', defaultCategory: 'new-energy' },
  { name: 'CleanTechnica', url: 'https://cleantechnica.com/feed/', region: 'overseas', defaultCategory: 'new-energy' },
  // ========== 医疗健康 ==========
  { name: 'Stat News', url: 'https://www.statnews.com/feed/', region: 'overseas', defaultCategory: 'healthcare' },
  { name: 'FierceBiotech', url: 'https://www.fiercebiotech.com/rss', region: 'overseas', defaultCategory: 'healthcare' },
  { name: 'MedTech', url: 'https://www.medtechdive.com/rss/news/', region: 'overseas', defaultCategory: 'healthcare' },
  { name: 'HealthTech', url: 'https://www.healthtechzone.com/rss/feed.xml', region: 'overseas', defaultCategory: 'healthcare' },
  { name: 'Medscape', url: 'https://www.medscape.com/rss/news', region: 'overseas', defaultCategory: 'healthcare' },
  { name: '丁香园', url: 'https://rsshub.rssforever.com/dxy/dxyc', region: 'domestic', defaultCategory: 'healthcare' },
  { name: '医学界', url: 'https://rsshub.rssforever.com/yxj/xwzx', region: 'domestic', defaultCategory: 'healthcare' },
  { name: '健康界', url: 'https://rsshub.rssforever.com/cn-healthcare/news', region: 'domestic', defaultCategory: 'healthcare' },
  { name: '36氪医疗', url: 'https://rsshub.rssforever.com/36kr/motif/5474', region: 'domestic', defaultCategory: 'healthcare' },
  // ========== 政策法规与财经 ==========
  { name: 'Reuters Business', url: 'https://www.reuters.com/business/feed/', region: 'overseas', defaultCategory: 'policy-finance' },
  { name: 'Bloomberg Technology', url: 'https://feeds.bloomberg.com/technology/news.rss', region: 'overseas', defaultCategory: 'policy-finance' },
  { name: 'Financial Times Tech', url: 'https://www.ft.com/technology?format=rss', region: 'overseas', defaultCategory: 'policy-finance' },
  { name: 'Legaltech News', url: 'https://www.law.com/legaltechnews/feed/', region: 'overseas', defaultCategory: 'policy-finance' },
  { name: 'Law.com', url: 'https://www.law.com/feed/', region: 'overseas', defaultCategory: 'policy-finance' },
  { name: 'Reuters Legal', url: 'https://www.reuters.com/legal/feed/', region: 'overseas', defaultCategory: 'policy-finance' },
  { name: '中国法院网', url: 'https://www.chinacourt.org/article/rss.shtml', region: 'domestic', defaultCategory: 'policy-finance' },
  { name: '北大法宝', url: 'https://rsshub.rssforever.com/pkulaw/chl', region: 'domestic', defaultCategory: 'policy-finance' },
  { name: 'NIST Technology', url: 'https://www.nist.gov/news-events/technology-news/feed', region: 'overseas', defaultCategory: 'policy-finance' },
  { name: '欧盟AI法案', url: 'https://digital-strategy.ec.europa.eu/en/artificial-intelligence', region: 'overseas', defaultCategory: 'policy-finance' },
  { name: '工信部', url: 'https://rsshub.rssforever.com/miit/xwzx', region: 'domestic', defaultCategory: 'policy-finance' },
  { name: '科技部', url: 'https://rsshub.rssforever.com/most/kjyw', region: 'domestic', defaultCategory: 'policy-finance' },
  { name: '法制日报', url: 'https://rsshub.rssforever.com/legaldaily/xwsf', region: 'domestic', defaultCategory: 'policy-finance' },
  // ========== 经济与股市 ==========
  { name: '36氪', url: 'https://www.36kr.com/feed', region: 'domestic', defaultCategory: 'economy-stock' },
  { name: 'IT之家', url: 'https://www.ithome.com/rss', region: 'domestic', defaultCategory: 'economy-stock' },
  { name: '财新网', url: 'https://rsshub.rssforever.com/caixin/latest', region: 'domestic', defaultCategory: 'economy-stock' },
  { name: 'Seeking Alpha', url: 'https://seekingalpha.com/feed/feed.xml', region: 'overseas', defaultCategory: 'economy-stock' },
  { name: '经济观察网', url: 'https://www.eeo.com.cn/rss.xml', region: 'domestic', defaultCategory: 'economy-stock' },
  { name: 'MarketWatch', url: 'https://www.marketwatch.com/rss/topstories', region: 'overseas', defaultCategory: 'economy-stock' },
  { name: 'Kiplinger', url: 'https://www.kiplinger.com/rss/feed', region: 'overseas', defaultCategory: 'economy-stock' },
  { name: 'Investing.com', url: 'https://www.investing.com/rss/news_25.rss', region: 'overseas', defaultCategory: 'economy-stock' },
  { name: '中国新闻网', url: 'https://www.chinanews.com/rss/finance.xml', region: 'domestic', defaultCategory: 'economy-stock' },
  { name: '人民网财经', url: 'https://www.people.com.cn/rss/finance.xml', region: 'domestic', defaultCategory: 'economy-stock' },
  { name: 'Wall Street Journal', url: 'https://feeds.a.dj.com/rss/RSSMarketsMain.xml', region: 'overseas', defaultCategory: 'economy-stock' },
  { name: 'Bloomberg Markets', url: 'https://feeds.bloomberg.com/markets/news.rss', region: 'overseas', defaultCategory: 'economy-stock' },
  { name: 'Reuters Finance', url: 'https://www.reuters.com/business/finance/feed/', region: 'overseas', defaultCategory: 'economy-stock' },
  { name: 'CNBC Markets', url: 'https://www.cnbc.com/id/10000664/device/rss/rss.html', region: 'overseas', defaultCategory: 'economy-stock' },
  { name: 'Financial Times Markets', url: 'https://www.ft.com/markets?format=rss', region: 'overseas', defaultCategory: 'economy-stock' },
  { name: "Barron's", url: 'https://www.barrons.com/rss.xml', region: 'overseas', defaultCategory: 'economy-stock' },
  { name: '第一财经', url: 'https://www.yicai.com/rss/', region: 'domestic', defaultCategory: 'economy-stock' },
  { name: '华尔街见闻', url: 'https://rss.wallstreetcn.com/latest', region: 'domestic', defaultCategory: 'economy-stock' },
  { name: 'Motley Fool', url: 'https://www.fool.com/the-motley-fool/rss.aspx', region: 'overseas', defaultCategory: 'economy-stock' },
  { name: '证券时报', url: 'https://rsshub.rssforever.com/stcn/xwzx', region: 'domestic', defaultCategory: 'economy-stock' },
  { name: '中国证券报', url: 'https://rsshub.rssforever.com/cs/zjxw', region: 'domestic', defaultCategory: 'economy-stock' },
  { name: '东方财富', url: 'https://rsshub.rssforever.com/eastmoney/cyxw', region: 'domestic', defaultCategory: 'economy-stock' },
  { name: '雪球', url: 'https://rsshub.rssforever.com/xueqiu/user/2588023793', region: 'domestic', defaultCategory: 'economy-stock' },
  { name: 'ArXiv Quantitative Finance', url: 'https://export.arxiv.org/rss/q-fin', region: 'global', defaultCategory: 'economy-stock' },
  { name: 'BBC World', url: 'https://feeds.bbci.co.uk/news/world/rss.xml', region: 'overseas', defaultCategory: 'economy-stock' },
  { name: 'BBC Business', url: 'https://feeds.bbci.co.uk/news/business/rss.xml', region: 'overseas', defaultCategory: 'economy-stock' },
  { name: 'Guardian International', url: 'https://www.theguardian.com/world/rss', region: 'overseas', defaultCategory: 'economy-stock' },
  { name: 'SkyNews World', url: 'https://feeds.skynews.com/feeds/rss/world.xml', region: 'overseas', defaultCategory: 'economy-stock' },
  { name: 'Reuters TopNews', url: 'https://feeds.reuters.com/reuters/topNews', region: 'overseas', defaultCategory: 'economy-stock' },
  { name: 'Reuters World', url: 'https://feeds.reuters.com/reuters/worldNews', region: 'overseas', defaultCategory: 'economy-stock' },
  { name: 'CNN World', url: 'http://rss.cnn.com/rss/cnn_world.rss', region: 'overseas', defaultCategory: 'economy-stock' },
  { name: 'NYT Homepage', url: 'https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml', region: 'overseas', defaultCategory: 'economy-stock' },
  { name: 'Washington Post World', url: 'https://feeds.washingtonpost.com/rss/world', region: 'overseas', defaultCategory: 'economy-stock' },
  // （已移除中国官方代理源：原指向人民网/新华网/36氪等代理URL，不再误导用户）
  // ========== P0 新增：海外AI独角兽/厂商官方（已移除代理源） ==========
  { name: 'Databricks Blog', url: 'https://www.databricks.com/feed', region: 'overseas', defaultCategory: 'ai-models', sourceType: 'vendor_official', tags: ['海外','Databricks','数据+AI'] },
  // （已移除：xAI/Groq/Perplexity/Character.AI/Inflection/Replicate/Together AI/Fireworks/Modal/Cerebras/Tenstorrent 等代理源）
  // （已移除国内AI大厂代理源：原18个源指向量子位/36氪/InfoQ/钛媒体/IT之家/开源中国等代理URL）
  // ========== P1 新增：产业联盟/专业媒体（已移除代理源） ==========
  { name: 'Partnership on AI', url: 'https://www.partnershiponai.org/feed/', region: 'global', defaultCategory: 'policy-finance', sourceType: 'industry_association', tags: ['国际','AI合作','AI治理'] },
  // （已移除：AI Alliance 重复源、SemiAnalysis/The Next Platform/WikiChip/半导体观察/CB Insights/PitchBook/a16z 等代理源）
  { name: 'CNCF Blog', url: 'https://www.cncf.io/blog/feed/', region: 'global', defaultCategory: 'cloud', sourceType: 'industry_association', tags: ['国际','CNCF','云原生'] },
  { name: 'Kubernetes Blog', url: 'https://kubernetes.io/feed.xml', region: 'global', defaultCategory: 'cloud', sourceType: 'industry_association', tags: ['国际','K8s','容器编排'] },
  { name: 'Terraform / HashiCorp Blog', url: 'https://www.hashicorp.com/blog/feed.xml', region: 'global', defaultCategory: 'cloud', sourceType: 'vendor_official', tags: ['国际','Terraform','IaC'] },
  { name: 'Sequoia Capital Blog', url: 'https://www.sequoiacap.com/rss', region: 'overseas', defaultCategory: 'economy-stock', sourceType: 'professional_media', tags: ['海外','红杉资本','风投'] },
  { name: 'NPR Global', url: 'https://feeds.npr.org/1001/rss.xml', region: 'overseas', defaultCategory: 'economy-stock' },
  { name: 'CNBC Global', url: 'https://www.cnbc.com/id/100003114/device/rss/rss.xml', region: 'overseas', defaultCategory: 'economy-stock' },
  { name: 'DW English', url: 'https://rss.dw.com/rdf/rss-en-all', region: 'overseas', defaultCategory: 'economy-stock' },
  { name: 'France24 International', url: 'https://www.france24.com/en/rss', region: 'overseas', defaultCategory: 'economy-stock' },
  { name: 'CBC World', url: 'https://www.cbc.ca/rss/world.xml', region: 'overseas', defaultCategory: 'economy-stock' },
  { name: 'GlobalNews World', url: 'https://globalnews.ca/world/feed/', region: 'overseas', defaultCategory: 'economy-stock' },
  { name: 'NHK World', url: 'https://www3.nhk.or.jp/rss/news/cat0.xml', region: 'overseas', defaultCategory: 'economy-stock' },
  { name: 'SCMP International', url: 'https://www.scmp.com/rss/91/feed', region: 'overseas', defaultCategory: 'economy-stock' },
  { name: 'RT International', url: 'https://www.rt.com/rss/news/', region: 'overseas', defaultCategory: 'economy-stock' },
  // ========== 游戏娱乐 ==========
  { name: 'Steam News', url: 'https://store.steampowered.com/feeds/news.xml', region: 'global', defaultCategory: 'game-entertain' },
  { name: 'Ars Technica Gaming', url: 'https://feeds.arstechnica.com/arstechnica/gaming', region: 'overseas', defaultCategory: 'game-entertain' },
  { name: 'Rock Paper Shotgun', url: 'https://www.rockpapershotgun.com/feed', region: 'overseas', defaultCategory: 'game-entertain' },
  { name: 'Nintendo Life', url: 'https://www.nintendolife.com/feeds/news', region: 'overseas', defaultCategory: 'game-entertain' },
  { name: 'TechCrunch Gaming', url: 'https://techcrunch.com/category/gaming/feed/', region: 'overseas', defaultCategory: 'game-entertain' },
  // ========== 影视娱乐圈 ==========
  { name: 'Variety', url: 'https://variety.com/feed/', region: 'overseas', defaultCategory: 'showbiz' },
  { name: 'Hollywood Reporter', url: 'https://www.hollywoodreporter.com/feed/', region: 'overseas', defaultCategory: 'showbiz' },
  { name: 'TMZ', url: 'https://www.tmz.com/rss.xml', region: 'overseas', defaultCategory: 'showbiz' },
  { name: 'The Guardian Film', url: 'https://www.theguardian.com/film/rss', region: 'overseas', defaultCategory: 'showbiz' },
  { name: 'BBC Entertainment', url: 'https://feeds.bbci.co.uk/news/entertainment_and_arts/rss.xml', region: 'overseas', defaultCategory: 'showbiz' },
  { name: 'Rolling Stone', url: 'https://www.rollingstone.com/feed/', region: 'overseas', defaultCategory: 'showbiz' },
  // ========== 动漫二次元 ==========
  { name: 'Crunchyroll News', url: 'https://feeds.feedburner.com/crunchyroll/animenews', region: 'overseas', defaultCategory: 'anime-acg' },
  { name: 'ComicBook.com', url: 'https://comicbook.com/feed/', region: 'overseas', defaultCategory: 'anime-acg' },
  // ========== 物联网与5G ==========
  { name: 'IoT World Today', url: 'https://www.iotworldtoday.com/feed', region: 'overseas', defaultCategory: 'iot-5g' },
  { name: 'Light Reading', url: 'https://www.lightreading.com/rss.asp', region: 'overseas', defaultCategory: 'iot-5g' },
  // ========== 太空探索 ==========
  { name: 'SpaceNews', url: 'https://spacenews.com/feed/', region: 'overseas', defaultCategory: 'space' },
  { name: 'Space.com', url: 'https://www.space.com/feeds/all', region: 'overseas', defaultCategory: 'space' },
  // ========== 智能汽车 ==========
  { name: 'The Verge Automotive', url: 'https://www.theverge.com/transportation/rss/index.xml', region: 'overseas', defaultCategory: 'automotive' },
  // ========== 教育科技 ==========
  { name: 'EdSurge', url: 'https://www.edsurge.com/rss.xml', region: 'overseas', defaultCategory: 'education-tech' },
  { name: 'TechCrunch Education', url: 'https://techcrunch.com/category/education/feed/', region: 'overseas', defaultCategory: 'education-tech' },
  // ========== 金融科技 ==========
  { name: 'Cointelegraph', url: 'https://cointelegraph.com/rss', region: 'overseas', defaultCategory: 'fintech' },
  { name: 'The Block', url: 'https://www.theblock.co/rss', region: 'overseas', defaultCategory: 'fintech' },
  { name: 'Popular Mechanics', url: 'https://www.popularmechanics.com/rss/', region: 'overseas', defaultCategory: 'fintech' },
  // ========== 数据科学 ==========
  { name: 'KDnuggets', url: 'https://www.kdnuggets.com/feed', region: 'overseas', defaultCategory: 'data-science' },
  { name: 'Towards Data Science', url: 'https://towardsdatascience.com/feed', region: 'overseas', defaultCategory: 'data-science' },
  // ========== 量子计算 ==========
  { name: 'Quantum Computing Report', url: 'https://quantumcomputingreport.com/feed/', region: 'overseas', defaultCategory: 'quantum' },
  // ========== 中文科技媒体 ==========
  { name: 'InfoQ CN', url: 'https://www.infoq.cn/feed', region: 'domestic', defaultCategory: 'china-tech' },
  { name: '虎嗅', url: 'https://www.huxiu.com/rss/0.xml', region: 'domestic', defaultCategory: 'china-tech' },
  { name: '钛媒体', url: 'https://www.tmtpost.com/feed', region: 'domestic', defaultCategory: 'china-tech' },
  { name: '联合早报', url: 'https://www.zaobao.com/rss.xml', region: 'domestic', defaultCategory: 'china-tech' },
  { name: '德国之声中文', url: 'https://rss.dw.com/rdf/rss-zh-all', region: 'domestic', defaultCategory: 'china-tech' },
  { name: '香港电台国际', url: 'https://news.rthk.hk/rthk/ch/rss/international.xml', region: 'domestic', defaultCategory: 'china-tech' },
  { name: '观察者网', url: 'https://www.guancha.cn/rss', region: 'domestic', defaultCategory: 'china-tech' },
  // ========== 新增：国内高质量科技/安全媒体 ==========
  { name: '极客公园', url: 'https://www.geekpark.net/rss', region: 'domestic', defaultCategory: 'china-tech', sourceType: 'tech_media', tags: ['国内','极客公园','科技'] },
  { name: '雷锋网', url: 'https://www.leiphone.com/feed', region: 'domestic', defaultCategory: 'china-tech', sourceType: 'tech_media', tags: ['国内','雷锋网','AI/硬件'] },
  { name: '博客园', url: 'https://www.cnblogs.com/rss', region: 'domestic', defaultCategory: 'open-source', sourceType: 'developer_community', tags: ['国内','博客园','开发者'] },
  { name: 'FreeBuf', url: 'https://www.freebuf.com/feed', region: 'domestic', defaultCategory: 'cybersecurity', sourceType: 'professional_media', tags: ['国内','FreeBuf','安全'] },
  // ========== 新增：社媒 / 视频平台（Folo/RSSHub 式跨源订阅，补 M4 非 RSS 源盲区） ==========
  { name: 'X @OpenAI', url: 'https://rsshub.rssforever.com/twitter/user/OpenAI', region: 'overseas', defaultCategory: 'ai-models', sourceType: 'social_platform', tags: ['海外','OpenAI','X'] },
  { name: 'X @AnthropicAI', url: 'https://rsshub.rssforever.com/twitter/user/AnthropicAI', region: 'overseas', defaultCategory: 'ai-models', sourceType: 'social_platform', tags: ['海外','Anthropic','X'] },
  { name: 'X @GoogleDeepMind', url: 'https://rsshub.rssforever.com/twitter/user/GoogleDeepMind', region: 'overseas', defaultCategory: 'ai-models', sourceType: 'social_platform', tags: ['海外','DeepMind','X'] },
  { name: 'X @NVIDIA', url: 'https://rsshub.rssforever.com/twitter/user/NVIDIA', region: 'overseas', defaultCategory: 'ai-models', sourceType: 'social_platform', tags: ['海外','NVIDIA','X'] },
  { name: 'X @ylecun', url: 'https://rsshub.rssforever.com/twitter/user/ylecun', region: 'overseas', defaultCategory: 'silicon-valley', sourceType: 'social_platform', tags: ['海外','Yann LeCun','X'] },
  { name: 'X @demishassabis', url: 'https://rsshub.rssforever.com/twitter/user/demishassabis', region: 'overseas', defaultCategory: 'silicon-valley', sourceType: 'social_platform', tags: ['海外','Demis Hassabis','X'] },
  { name: 'YouTube @OpenAI', url: 'https://rsshub.rssforever.com/youtube/user/openai', region: 'overseas', defaultCategory: 'ai-models', sourceType: 'video_platform', tags: ['海外','OpenAI','YouTube'] },
  { name: 'YouTube @DeepMind', url: 'https://rsshub.rssforever.com/youtube/user/DeepMind', region: 'overseas', defaultCategory: 'ai-models', sourceType: 'video_platform', tags: ['海外','DeepMind','YouTube'] },
  { name: 'YouTube @TwoMinutePapers', url: 'https://rsshub.rssforever.com/youtube/user/TwoMinutePapers', region: 'overseas', defaultCategory: 'research', sourceType: 'video_platform', tags: ['海外','论文解读','YouTube'] },
  { name: 'YouTube @YannLeCun', url: 'https://rsshub.rssforever.com/youtube/user/YannLeCun', region: 'overseas', defaultCategory: 'silicon-valley', sourceType: 'video_platform', tags: ['海外','Yann LeCun','YouTube'] },
];;

export const TRENDING_SOURCES = [
  // === 国内平台 ===
  // 科技媒体热门
  { name: '36氪', url: 'https://36kr.com/feed', region: 'domestic', platform: '36氪' },
  { name: '36氪快讯', url: `${RSSHUB_BASE}/36kr/newsflashes`, region: 'domestic', platform: '36氪' },
  { name: '少数派', url: 'https://sspai.com/feed', region: 'domestic', platform: '少数派' },
  { name: '爱范儿', url: 'https://www.ifanr.com/feed', region: 'domestic', platform: '爱范儿' },
  { name: '品玩', url: 'https://www.pingwest.com/feed', region: 'domestic', platform: '品玩' },
  { name: '虎扑', url: 'https://bbs.hupu.com/feed', region: 'domestic', platform: '虎扑' },
  // 热门排行榜
  { name: 'IT之家 24h 热榜', url: `${RSSHUB_BASE}/ithome/ranking/24h`, region: 'domestic', platform: 'IT之家' },

  // === 国际平台 ===
  // 技术社区热榜
  { name: 'Hacker News Top', url: 'https://hnrss.org/frontpage', region: 'global', platform: 'Hacker News' },
  { name: 'Hacker News Best', url: 'https://hnrss.org/best', region: 'global', platform: 'Hacker News' },
  { name: 'Dev.to', url: 'https://dev.to/feed', region: 'global', platform: 'Dev.to' },
  { name: 'Lobsters', url: 'https://lobste.rs/rss', region: 'global', platform: 'Lobsters' },
  // 新产品/项目发现
  { name: 'Product Hunt', url: 'https://www.producthunt.com/feed', region: 'global', platform: 'Product Hunt' },
  { name: 'GitHub Blog', url: 'https://github.blog/feed/', region: 'global', platform: 'GitHub' },
  // 顶级科技媒体
  { name: 'TechCrunch', url: 'https://techcrunch.com/feed/', region: 'global', platform: 'TechCrunch' },
  { name: 'The Verge', url: 'https://www.theverge.com/rss/index.xml', region: 'global', platform: 'The Verge' },
  { name: 'Ars Technica', url: 'https://arstechnica.com/feed/', region: 'global', platform: 'Ars Technica' },
  { name: 'Wired', url: 'https://www.wired.com/feed/rss', region: 'global', platform: 'Wired' },
  { name: 'MIT Technology Review', url: 'https://www.technologyreview.com/feed/', region: 'global', platform: 'MIT Review' },
  // 综合科技/极客
  { name: 'Engadget', url: 'https://www.engadget.com/rss.xml', region: 'global', platform: 'Engadget' },
  { name: 'Slashdot', url: 'https://rss.slashdot.org/Slashdot/slashdotMain', region: 'global', platform: 'Slashdot' },
  { name: 'Smashing Magazine', url: 'https://www.smashingmagazine.com/feed/', region: 'global', platform: 'Smashing Mag' },
];

export const CATEGORY_GROUPS = [
  {
    id: 'tech-ai',
    label: '科技前沿',
    icon: 'flask',
    categories: ['ai-models', 'research', 'open-source', 'data-science', 'quantum', 'cybersecurity', 'chips-compute']
  },
  {
    id: 'hardware-consumer',
    label: '消费电子',
    icon: 'device',
    categories: ['devices', 'robotics', 'iot-5g', 'metaverse-xr', 'automotive']
  },
  {
    id: 'industry-economy',
    label: '产业经济',
    icon: 'building',
    categories: ['silicon-valley', 'china-tech', 'policy-finance', 'fintech', 'economy-stock']
  },
  {
    id: 'entertainment',
    label: '娱乐文化',
    icon: 'star',
    categories: ['gaming', 'game-entertain', 'showbiz', 'anime-acg']
  },
  {
    id: 'lifestyle-health',
    label: '生活健康',
    icon: 'heart',
    categories: ['space', 'new-energy', 'climate-esg', 'healthcare', 'education-tech']
  }
];

export const CATEGORIES = [
  { id: 'all', label: '全部内容' },
  { id: 'ai-models', label: 'AI 大模型' },
  { id: 'research', label: '科研前沿' },
  { id: 'open-source', label: '开源生态' },
  { id: 'data-science', label: '数据科学' },
  { id: 'quantum', label: '量子计算' },
  { id: 'cybersecurity', label: '网络安全' },
  { id: 'chips-compute', label: '芯片半导体' },
  { id: 'devices', label: '硬件数码' },
  { id: 'robotics', label: '机器人' },
  { id: 'iot-5g', label: '物联网5G' },
  { id: 'silicon-valley', label: '硅谷欧美' },
  { id: 'china-tech', label: '国内大厂' },
  { id: 'policy-finance', label: '政策财经' },
  { id: 'fintech', label: '金融科技' },
  { id: 'space', label: '太空探索' },
  { id: 'new-energy', label: '新能源' },
  { id: 'climate-esg', label: '气候ESG' },
  { id: 'gaming', label: '游戏电竞' },
  { id: 'metaverse-xr', label: '元宇宙XR' },
  { id: 'healthcare', label: '医疗健康' },
  { id: 'education-tech', label: '教育科技' },
  { id: 'agriculture-tech', label: '农业科技' },
  { id: 'cloud', label: '云计算' },
  { id: 'automotive', label: '智能汽车' },
  { id: 'economy-stock', label: '经济股市' },
  { id: 'game-entertain', label: '游戏娱乐' },
  { id: 'showbiz', label: '影视娱乐圈' },
  { id: 'anime-acg', label: '动漫二次元' }
];

export const MODES = [
  { id: 'all', label: '全部内容' },
  { id: 'flash', label: '实时快讯' },
  { id: 'deep', label: '深度解读' },
  { id: 'technical', label: '技术干货' }
];

export const CATEGORY_RULES = [
  ['ai-models', /\b(ai|artificial intelligence|llm|gpt|model|agent|deepmind|openai|anthropic|gemini|claude|大模型|人工智能|智能体|machine learning|neural|transformer)\b/i],
  ['research', /\b(research|paper|study|scientist|arxiv|mit|科研|论文|研究|nature|science|academic)\b/i],
  ['open-source', /\b(open source|github|linux|rust|python|kubernetes|developer|repo|开源|开发者|docker|k8s|javascript|typescript)\b/i],
  ['data-science', /\b(data science|big data|analytics|machine learning|deep learning|数据科学|大数据|分析|算法工程师|data analyst|data engineer)\b/i],
  ['quantum', /\b(quantum|qubit|quantum computing|量子|量子计算|量子通信|量子纠缠|superposition|entanglement)\b/i],
  ['cybersecurity', /\b(security|hack|breach|vulnerability|exploit|ransomware|phishing|malware|cyber|attack|漏洞|安全|黑客|勒索软件|钓鱼|数据泄露|隐私)\b/i],
  ['chips-compute', /\b(chip|semiconductor|gpu|nvidia|amd|intel|tsmc|compute|cuda|芯片|半导体|算力|processor|cpu|tpu|silicon|asic|fpga|制程|光刻)\b/i],
  ['devices', /\b(iphone|android|device|wearable|hardware|phone|laptop|数码|手机|硬件|macbook|ipad|watch|headphone)\b/i],
  ['robotics', /\b(robot|robotics|humanoid|autonomous|机器人|自动驾驶|drone|automation|boston dynamics|协作机器人)\b/i],
  ['iot-5g', /\b(iot|internet of things|5g|sensor|edge computing|物联网|传感器|边缘计算|smart city|智慧城市|connected device)\b/i],
  ['silicon-valley', /\b(silicon valley|startup|tech company|硅谷|科技巨头|venture capital|unicorn)\b/i],
  ['china-tech', /\b(alibaba|tencent|baidu|bytedance|huawei|xiaomi|china|阿里|腾讯|百度|字节|华为|小米|国内|jd|京东|美团|didi)\b/i],
  ['policy-finance', /\b(policy|regulation|funding|ipo|investment|venture|finance|stock|market|earnings|gdp|inflation|fed|央行|融资|政策|监管|投资|金融|股票|财报|股市|利率|宏观经济|legislation)\b/i],
  ['fintech', /\b(fintech|payment|blockchain|cryptocurrency|bitcoin|defi|digital banking|neobank|金融科技|支付|区块链|数字货币|银行科技|信贷科技|保险科技)\b/i],
  ['space', /\b(space|nasa|spacex|rocket|satellite|mars|moon|starlink|blue origin|太空|航天|火箭|卫星|火星|月球|发射|轨道|starship)\b/i],
  ['new-energy', /\b(solar|wind|ev|battery|lithium|carbon|储能|光伏|锂电|新能源|碳中和|清洁能源|电动车|solar energy|wind power|hydrogen|hydrogen fuel)\b/i],
  ['climate-esg', /\b(climate|esg|carbon neutral|sustainability|green finance|emission|气候|碳减排|esg|可持续|绿色金融|碳中和|温室气体|减排)\b/i],
  ['gaming', /\b(gaming|esports|video game|nintendo|playstation|xbox|steam|unreal engine|unity|游戏|电竞|主机游戏|手游|游戏引擎|game developer)\b/i],
  ['metaverse-xr', /\b(metaverse|vr|ar|xr|virtual reality|augmented reality|oculus|vision pro|spatial computing|元宇宙|虚拟现实|增强现实|空间计算|headset)\b/i],
  ['healthcare', /\b(health|medical|biotech|pharma|drug|clinical|医疗|健康|生物|制药|基因|therapy|diagnosis|patient|hospital|disease|cancer|数字医疗|ai医疗)\b/i],
  ['education-tech', /\b(edtech|online learning|e-learning|mooc|education technology|教育科技|在线教育|数字教育|edtech|慕课|教育平台)\b/i],
  ['agriculture-tech', /\b(agtech|precision agriculture|vertical farming|smart farming|agricultural technology|农业科技|精准农业|垂直农场|智慧农业|数字农业)\b/i],
  ['cloud', /\b(cloud|aws|azure|google cloud|serverless|database|云计算|云服务|kubernetes|docker|devops|saas|paas|iaas)\b/i],
  ['automotive', /\b(automotive|tesla|ev|self-driving|autonomous vehicle|smart car|汽车|电动车|自动驾驶|智能汽车|车载系统|车联网)\b/i],
  ['economy-stock', /\b(stock|market|ipo|trading|investment|earnings|gdp|inflation|fed|央行|融资|股票|股市|财报|利率|宏观经济|证券|基金|期货|港股|美股|a股|债券|汇率|财经|经济)\b/i],
  ['game-entertain', /\b(game|gaming|esports|playstation|xbox|nintendo|steam|unreal|unity|游戏|电竞|手游|主机|端游|网游|steam|任天堂|索尼|微软|腾讯游戏|网易游戏|米哈游|原神|王者荣耀)\b/i],
  ['showbiz', /\b(movie|film|tv show|celebrity|actor|actress|director|oscar|grammy|emmy|电影|电视剧|演员|导演|明星|综艺|颁奖|票房|好莱坞|bollywood|netflix|hbo|disney)\b/i],
  ['anime-acg', /\b(anime|manga|otaku|cosplay|light novel|vtuber|waifu|二次元|动漫|番剧|漫画|轻小说|cosplay|手办|谷子|同人|本子|新番|漫展|acg)\b/i]
];

export const TAG_RULES = [
  ['AI', /\b(ai|artificial intelligence|llm|gpt|model|agent|大模型|人工智能)\b/i],
  ['Chip', /\b(chip|gpu|semiconductor|nvidia|芯片|半导体|算力)\b/i],
  ['Open Source', /\b(open source|github|linux|开源)\b/i],
  ['Cloud', /\b(cloud|aws|azure|serverless|云)\b/i],
  ['Research', /\b(research|paper|arxiv|论文|研究)\b/i],
  ['Policy', /\b(policy|regulation|监管|政策)\b/i],
  ['Funding', /\b(funding|investment|ipo|融资|投资)\b/i],
  ['Hardware', /\b(device|hardware|phone|laptop|硬件|手机)\b/i],
  ['Robotics', /\b(robot|robotics|机器人)\b/i],
  ['Mobile', /\b(iphone|android|ios|app store)\b/i],
  ['Security', /\b(security|漏洞|安全|cyber|hack)\b/i],
  ['Startup', /\b(startup|创业|venture|funding)\b/i],
  ['New Energy', /\b(solar|wind|ev|battery|新能源|储能|光伏|锂电)\b/i],
  ['Healthcare', /\b(health|medical|biotech|pharma|drug|医疗|健康|生物|制药)\b/i],
  ['Finance', /\b(finance|stock|market|earnings|金融|股票|财报|股市)\b/i],
  ['Space', /\b(space|nasa|spacex|rocket|satellite|太空|航天|火箭|卫星)\b/i],
  ['Gaming', /\b(gaming|esports|video game|游戏|电竞)\b/i],
  ['Climate', /\b(climate|esg|carbon|sustainability|气候|碳减排|esg|可持续)\b/i],
  ['Automotive', /\b(automotive|tesla|ev|self-driving|汽车|电动车|自动驾驶)\b/i],
  ['Data', /\b(data science|big data|analytics|数据科学|大数据|算法)\b/i],
  ['Quantum', /\b(quantum|量子计算|qubit)\b/i],
  ['IoT', /\b(iot|5g|sensor|物联网|传感器|边缘计算)\b/i],
  ['Fintech', /\b(fintech|payment|blockchain|cryptocurrency|金融科技|支付|区块链)\b/i],
  ['Metaverse', /\b(metaverse|vr|ar|xr|虚拟现实|元宇宙)\b/i],
  ['Education', /\b(edtech|online learning|教育科技|在线教育)\b/i],
  ['Agriculture', /\b(agtech|precision agriculture|农业科技|智慧农业)\b/i]
];

// ========== 图片黑名单 ==========
export const IMAGE_BLACKLIST_RE = /(\/|^)(ads|advert|banner|sponsor|promo|tracking|pixel|beacon|stat|analytics|share-bar|social-bar|gravatar|feedburner|rss|newsletter-signup|popup|overlay|interstitial|cdnp|cloudfront\.net\/images\/ui|fb-[a-z]|tw-[a-z]|linkedin-[a-z]|pinterest-[a-z]|buffer-[a-z]|addthis|sharethis|disqus|wp-emoticon|mstile|apple-touch-icon|android-chrome|safari-pinned|og-image-default|placeholder|stock|ticker|chart-bar|subscribe|related-post|sidebar|widget|newsletter|popup-icon|notification|push|web-push|logo|brand|identity|template|default|generic|common|shared|global|header-bg|footer-bg|nav-bg|hero-bg|banner-bg|site-logo|company-logo|organization-logo)\b/i;
export const IMAGE_BLACKLIST_DOMAINS = /\/\/(feedburner\.|gravatar\.|disqus\.|addthis\.|sharethis\.|buffer\.|pixel\.|tracking\.|analytics\.|doubleclick\.|adsense\.|adnxs\.|moatads\.|chartbeat\.|newrelic\.|pingdom\.|taboola\.|outbrain\.|zemanta\.|scoopit\.|logo\.|brand\.|identity\.|template\.|default\.|generic\.|common\.|shared\.|global\.)/i;
export const IMAGE_MIN_DIM_HINT = /width=["']([0-9]+)["']|height=["']([0-9]+)["']/i;

// 懒加载图片属性
export const LAZY_LOAD_ATTRS = ['data-src', 'data-original', 'data-lazy-src', 'data-img-src', 'data-url', 'data-lazy', 'data-aspect-url'];
