import { useCallback, useEffect, useState } from 'react';
async function request(path, options = {}) { const response = await fetch(`/api/chat/${path}`, { ...options, credentials: 'include', headers: { 'Content-Type': 'application/json', ...(options.headers || {}) } }); const payload = await response.json().catch(() => ({})); if (!response.ok || payload.ok === false) { const error = new Error(payload?.error?.message || '聊天服务请求失败'); error.status = response.status; throw error; } return payload.data || {}; }
export function useChat({ enabled = true } = {}) {
  const [conversations, setConversations] = useState([]); const [contacts, setContacts] = useState([]); const [activeId, setActiveId] = useState(null); const [messages, setMessages] = useState([]); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  const load = useCallback(async () => { if (!enabled) return; setLoading(true); setError(''); try { const [conversationData, contactData] = await Promise.all([request('conversations'), request('contacts')]); setConversations(conversationData.conversations || []); setContacts(contactData.contacts || []); } catch (e) { setError(e.message); } finally { setLoading(false); } }, [enabled]);
  const loadMessages = useCallback(async id => { if (!id) return; setActiveId(id); try { const data = await request(`conversations/${id}/messages`); setMessages(data.items || []); await request(`conversations/${id}/read`, { method: 'POST', body: '{}' }); } catch (e) { setError(e.message); } }, []);
  useEffect(() => { load().catch(() => {}); }, [load]);
  const createConversation = useCallback(async input => { const data = await request('conversations', { method: 'POST', body: JSON.stringify(input) }); setConversations(prev => [data.conversation, ...prev]); setActiveId(data.conversation.id); setMessages([]); return data.conversation; }, []);
  const sendMessage = useCallback(async ({ conversationId = activeId, body, kind = 'text', sharePayload = null }) => { const data = await request(`conversations/${conversationId}/messages`, { method: 'POST', body: JSON.stringify({ body, kind, sharePayload }) }); setMessages(prev => [...prev, data.message]); setConversations(prev => prev.map(item => item.id === conversationId ? { ...item, lastMessage: data.message, updatedAt: data.message.createdAt } : item)); return data.message; }, [activeId]);
  const addContact = useCallback(async contactId => { await request('contacts', { method: 'POST', body: JSON.stringify({ contactId }) }); return load(); }, [load]);
  const joinByCode = useCallback(async inviteCode => { const data = await request('conversations', { method: 'POST', body: JSON.stringify({ inviteCode }) }); setConversations(prev => [data.conversation, ...prev.filter(item => item.id !== data.conversation.id)]); setActiveId(data.conversation.id); return data.conversation; }, []);
  return { conversations, contacts, activeId, messages, loading, error, setError, load, loadMessages, createConversation, sendMessage, addContact, joinByCode };
}
