import { useEffect, useMemo, useState } from 'react';
import { useChat } from '../hooks/useChat.js';

const label = item => item?.displayName || item?.username || item?.title || '未命名会话';
export default function ChatPage({ user, pendingShare, onConsumeShare, onRequireAuth }) {
  const chat = useChat({ enabled: Boolean(user) }); const [draft, setDraft] = useState(''); const [search, setSearch] = useState(''); const [groupName, setGroupName] = useState(''); const [selectedContacts, setSelectedContacts] = useState([]); const [inviteCode, setInviteCode] = useState('');
  const active = useMemo(() => chat.conversations.find(item => item.id === chat.activeId), [chat.conversations, chat.activeId]);
  useEffect(() => { if (!user) return; if (!chat.activeId && chat.conversations[0]) chat.loadMessages(chat.conversations[0].id); }, [user, chat.activeId, chat.conversations, chat.loadMessages]);
  useEffect(() => { if (pendingShare && chat.activeId) { setDraft(pendingShare.title ? `分享：${pendingShare.title}` : '分享一条资讯'); } }, [pendingShare, chat.activeId]);
  if (!user) return <section className="chat-page chat-empty"><h1>团队聊天</h1><p>登录后与联系人、团队和群组交流，并把社区文章与资讯直接分享进会话。</p><button className="ai-primary-action" onClick={onRequireAuth}>登录开始聊天</button></section>;
  const send = async () => { const text = draft.trim(); if (!text && !pendingShare) return; await chat.sendMessage({ body: text || '分享内容', kind: pendingShare ? 'share' : 'text', sharePayload: pendingShare || null }); setDraft(''); onConsumeShare?.(); };
  const startDirect = async contact => { const conversation = await chat.createConversation({ kind: 'direct', memberIds: [contact.id], title: label(contact) }); await chat.loadMessages(conversation.id); };
  const createGroup = async () => { if (!selectedContacts.length) return; const conversation = await chat.createConversation({ kind: 'group', title: groupName || '新群聊', memberIds: selectedContacts }); setGroupName(''); setSelectedContacts([]); await chat.loadMessages(conversation.id); };
  return <section className="chat-page">
    <header className="chat-header"><div><span className="workbench-kicker">COLLABORATION</span><h1>团队聊天</h1><p>把高价值资讯带进私聊与群组，形成可追踪的协作上下文。</p></div><div className="chat-header-actions"><input value={inviteCode} onChange={e => setInviteCode(e.target.value)} placeholder="输入群邀请码" /><button onClick={() => chat.joinByCode(inviteCode).catch(e => chat.setError(e.message))}>加入群聊</button></div></header>
    {chat.error && <div className="chat-error">{chat.error}</div>}
    <div className="chat-layout"><aside className="chat-sidebar"><div className="chat-panel-title"><strong>会话</strong><button onClick={() => chat.load()}>刷新</button></div>{chat.loading && <div className="chat-muted">正在同步…</div>}{chat.conversations.map(item => <button key={item.id} className={`chat-conversation ${item.id === chat.activeId ? 'active' : ''}`} onClick={() => chat.loadMessages(item.id)}><span className="chat-avatar">{label(item).slice(0,1)}</span><span><strong>{label(item)}</strong><small>{item.lastMessage?.body || (item.kind === 'group' ? `${item.memberCount} 位成员` : '开始聊天')}</small></span></button>)}{!chat.conversations.length && <div className="chat-muted">还没有会话，从联系人发起聊天。</div>}</aside>
      <main className="chat-main">{active ? <><div className="chat-main-head"><div><strong>{label(active)}</strong><span>{active.kind === 'group' ? `${active.memberCount} 位成员` : '私聊'}</span></div><code>{active.inviteCode || ''}</code></div><div className="chat-messages">{chat.messages.map(message => <article key={message.id} className={`chat-message ${message.senderId === user.id ? 'mine' : ''}`}><div className="chat-message-meta">{message.senderName || (message.senderId === user.id ? '我' : '成员')} · {new Date(message.createdAt).toLocaleString()}</div>{message.kind === 'share' && <div className="chat-share-card"><span>分享内容</span><strong>{message.sharePayload?.title || message.body}</strong><small>{message.sharePayload?.type || '资讯'}</small></div>}<p>{message.body}</p></article>)}{!chat.messages.length && <div className="chat-muted">发送第一条消息，开始协作。</div>}</div><div className="chat-composer">{pendingShare && <div className="chat-share-pending">待分享：{pendingShare.title || '一条内容'} <button onClick={onConsumeShare}>取消</button></div>}<textarea value={draft} onChange={e => setDraft(e.target.value)} onKeyDown={e => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); send().catch(err => chat.setError(err.message)); } }} placeholder="输入消息，Enter 发送" /><button className="ai-primary-action" onClick={() => send().catch(err => chat.setError(err.message))}>发送</button></div></> : <div className="chat-muted chat-no-active">选择一个会话，或从右侧联系人发起聊天。</div>}</main>
      <aside className="chat-contacts"><div className="chat-panel-title"><strong>联系人</strong><input value={search} onChange={e => setSearch(e.target.value)} placeholder="搜索" /></div>{chat.contacts.filter(item => !search || `${item.displayName}${item.username}`.includes(search)).map(contact => <div key={contact.id} className="chat-contact"><span className="chat-avatar">{label(contact).slice(0,1)}</span><span><strong>{label(contact)}</strong><small>@{contact.username}</small></span><button onClick={() => startDirect(contact).catch(e => chat.setError(e.message))}>聊天</button></div>)}<div className="chat-group-create"><strong>创建群聊</strong><input value={groupName} onChange={e => setGroupName(e.target.value)} placeholder="群名称" />{chat.contacts.map(contact => <label key={contact.id}><input type="checkbox" checked={selectedContacts.includes(contact.id)} onChange={e => setSelectedContacts(prev => e.target.checked ? [...prev, contact.id] : prev.filter(id => id !== contact.id))} />{label(contact)}</label>)}<button onClick={() => createGroup().catch(e => chat.setError(e.message))}>创建群聊</button></div></aside>
    </div></section>;
}
